
#血的教训,一定不要用tab来空格!!!一定不要用tab来空格!!!一定不要用tab来空格!!!
server:
  port: 12000
spring:
  application:
    name: provider-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    dbcp2:
      min-idle: 5 #最小空闲数
      initial-size: 5 #初始连接数
      max-total: 20 #最大总连接数
      max-wait-millis: 200 #最长等待时间
      max-idle: 10 #最大空闲数

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
    eureka-server-connect-timeout-seconds: 10 #连接eureka server的超时时间
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-handlers-package: com.michael.common.entity
logging:
  level:
    com.michael.provider.user.dao.*: debug